  version: '2'
  services:
    mariadb:
      image: mariadb:10.3
      volumes:
        - ./db/mariadb:/docker-entrypoint-initdb.d
      environment:
         - MYSQL_ROOT_PASSWORD=my-secret-pw
         - MYSQL_USER=mysqluser
         - MYSQL_PASSWORD=mysqlpw
    oauth2-code:
      build: code/
      ports:
        - "6881:6881"
      volumes:
        - ./db/mariadb/config/oauth2-code:/config
      depends_on:
        - mariadb
      links:
        - mariadb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-code"
      #    env: "dev"
    oauth2-token:
      build: token/
      ports:
        - "6882:6882"
      volumes:
        - ./db/mariadb/config/oauth2-token:/config
      depends_on:
        - mariadb
      links:
        - mariadb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-token"
      #    env: "dev"
    oauth2-service:
      build: service/
      ports:
        - "6883:6883"
      volumes:
        - ./db/mariadb/config/oauth2-service:/config
      depends_on:
        - mariadb
      links:
        - mariadb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-service"
      #    env: "dev"
    oauth2-client:
      build: client/
      ports:
        - "6884:6884"
      volumes:
        - ./db/mariadb/config/oauth2-client:/config
      depends_on:
        - mariadb
      links:
        - mariadb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-client"
      #    env: "dev"
    oauth2-user:
      build: user/
      ports:
        - "6885:6885"
      volumes:
        - ./db/mariadb/config/oauth2-user:/config
      depends_on:
        - mariadb
      links:
        - mariadb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-user"
      #    env: "dev"
    oauth2-key:
      build: key/
      ports:
        - "6886:6886"
      volumes:
        - ./db/mariadb/config/oauth2-key:/config
      depends_on:
        - mariadb
      links:
        - mariadb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-key"
      #    env: "dev"
    oauth2-refresh-token:
      build: refresh-token/
      ports:
        - "6887:6887"
      volumes:
        - ./db/mariadb/config/oauth2-refresh-token:/config
      depends_on:
        - mariadb
      links:
        - mariadb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-refresh-token"
      #    env: "dev"
